[package]
name = "wfc"
version = "0.1.0"
edition = "2021"

[lib]
name = "wfc"
path = "src/lib.rs"
bench = false

[dependencies]
rand = "0.8"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "wfc_bench"
harness = false



